version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: dockerfile
    ports:
      - "3000:80" # Maps port 3000 on your machine to port 80 in the container
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
      dockerfile: dockerfile
    ports:
      - "5000:5000" # Maps port 5000
    environment:
      - MONGO_URI=mongodb://mongo:27017/event-db # MongoDB connection string
    depends_on:
      - mongo

  mongo:
    image: mongo:5.0
    container_name: mongo
    ports:
      - "27017:27017" # Maps MongoDB port
    volumes:
      - mongo-data:/data/db # Persist database data

volumes:
  mongo-data: