name : CI/CD for Event Management System

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build App
    runs-on : ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3  

      - name: Install Backend Dependencies
        run: |
          cd backend
          npm init -y
          npm install 
      
      - name : Install frontend Dependencies
        run : |
          cd frontend
          npm init -y
          npm install